version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:20.10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
            - node-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-deps-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  run_ui_tests:
    docker:
      - image: cimg/node:20.10-browsers
    steps:
      - attach_workspace:
          at: .
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Browser Installation
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run UI Tests (Nightwatch)
          command: npm run ci:ui
      - store_artifacts:
          path: UI/results_reports
          destination: ui-test-results
      - store_test_results:
          path: UI/results_reports

  run_api_tests:
    docker:
      - image: cimg/node:20.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Start Mock Auth Server
          command: |
            npm run dev > api_server.log 2>&1 &
            echo $! > server.pid
            sleep 5
      - run:
          name: Run API Tests (Jest)
          command: npm run ci:api
      - run:
          name: Stop Mock Auth Server
          command: |
            if [ -f server.pid ]; then
            kill $(cat server.pid) 2>/dev/null || echo "Process already stopped."
            fi
          when: always
      - store_artifacts:
          path: api-tests/reports
          destination: api-test-results
      - store_test_results:
          path: api-tests/reports

workflows:
  version: 2
  run_all_tests:
    jobs:
      - install_dependencies
      - run_ui_tests:
          requires:
            - install_dependencies
      - run_api_tests:
          requires:
            - install_dependencies
